Add support for POST for `/makeCall` endpoint
twilio/voice-quickstart-server-node pull request #4
Opened 2018-01-19 18:56 UTC by kbagchiGWC

test result 

```
2181-kbagchi:voice-quickstart-server-node-1 kbagchi$ curl "http://localhost:3000/makeCall?to=1234567890" -X GET
<?xml version="1.0" encoding="UTF-8"?><Response><Dial><Number callerId="1234567890">1234567890</Number></Dial></Response>2181-kbagchi:voice-quickstart-server-node-1 kbagchi$
2181-kbagchi:voice-quickstart-server-node-1 kbagchi$
2181-kbagchi:voice-quickstart-server-node-1 kbagchi$
2181-kbagchi:voice-quickstart-server-node-1 kbagchi$ curl "http://localhost:3000/makeCall?to=1234567890" -X POST
<?xml version="1.0" encoding="UTF-8"?><Response><Dial><Number callerId="1234567890">1234567890</Number></Dial></Response>2181-kbagchi:voice-quickstart-server-node-1 kbagchi$
2181-kbagchi:voice-quickstart-server-node-1 kbagchi$
2181-kbagchi:voice-quickstart-server-node-1 kbagchi$ curl "http://localhost:3000/makeCall?to=1234567890" -X PUT
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot PUT /makeCall</pre>
</body>
</html>
2181-kbagchi:voice-quickstart-server-node-1 kbagchi$

```

2018-01-29 15:39 UTC, idelgado requested changes

2018-01-29 15:39 UTC, idelgado commented on src/server.js
> +function placeCall(request, response) {
This implementation differs from `java` and `python`

2018-01-30 02:52 UTC, kbagchiGWC commented
Result : 
env)2181-kbagchi:voice-quickstart-server-python kbagchi$ export VOICE_SERVER_URL=https://6956eecb.ngrok.io; nosetests
.................
----------------------------------------------------------------------
Ran 17 tests in 11.015s

OK

2018-01-30 03:00 UTC, idelgado requested changes

2018-01-30 03:00 UTC, idelgado commented on src/server.js
> +  } else if (!isNaN(to)) {
Exclude `+` sign

2018-01-30 03:00 UTC, idelgado commented on src/server.js
> +  } else if (!isNaN(to)) {
Same here

2018-01-30 19:02 UTC, idelgado approved these changes

2018-01-30 20:50 UTC, idelgado approved these changes

2018-01-30 21:27 UTC, merged